container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org
  # Using auto allows to run go command from a directory containing module
  GO111MODULE: auto

test_task:
  modules_cache:
    folder: $GOPATH/pkg/mod
  tests_script:
   # go mod cannot be used outside modules
   - go version
   - go get github.com/iwdgo/testingfiles
   - go vet ./...
   - go test -cover ./...
   - go test -bench=. ./sumofconverts
  build_script: go build ./...
