container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

test_task:
  modules_cache:
    folder: $GOPATH/pkg/mod
  get_script: go get ./...
  build_script: go build ./...
  vet_script: go vet ./...
  test_script: go test ./...
